{"name": "Test creating workout with invalid data", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('mocker', <SubRequest 'mock_firebase' for <Coroutine test_create_invalid_workout>>)", "trace": "file W:\\pyProjects\\vitalSyncBackend-v2\\tests\\test_workouts.py, line 52\n  @allure.feature(\"Workouts\")\n  @allure.story(\"Create Workout\")\n  @allure.title(\"Test creating workout with invalid data\")\n  @pytest.mark.asyncio\n  async def test_create_invalid_workout(client, test_db, mock_firebase):\n      user = User(id=\"test_user_id\", email=\"test@example.com\")\n      test_db.add(user)\n      test_db.commit()\n\n      headers = {\"Authorization\": \"Bearer valid_token\"}\n      workout_data = {\n          \"name\": \"Invalid Workout\",\n          \"start_time\": \"2025-07-30T10:00:00\",\n          \"exercises\": [{\"name\": \"Push-up\", \"rest_time\": -60, \"sets\": []}]\n      }\n      response = await client.post(\"/api/v1/workouts\", json=workout_data, headers=headers)\n      assert response.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY\nfile W:\\pyProjects\\vitalSyncBackend-v2\\tests\\conftest.py, line 60\n  @pytest.fixture\n  def mock_firebase(mocker):\nE       fixture 'mocker' not found\n>       available fixtures: _session_event_loop, anyio_backend, anyio_backend_name, anyio_backend_options, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, doctest_namespace, event_loop, event_loop_policy, free_tcp_port, free_tcp_port_factory, free_udp_port, free_udp_port_factory, mock_firebase, mock_qdrant, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, test_db, tests/test_workouts.py::<event_loop>, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, unused_tcp_port, unused_tcp_port_factory, unused_udp_port, unused_udp_port_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nW:\\pyProjects\\vitalSyncBackend-v2\\tests\\conftest.py:60"}, "start": 1753961209003, "stop": 1753961209003, "uuid": "f75b609a-10cf-41a4-9cf8-1d874bc01b91", "historyId": "0da9fad095a4ec3af74bfe11fcf7806a", "testCaseId": "0da9fad095a4ec3af74bfe11fcf7806a", "fullName": "tests.test_workouts#test_create_invalid_workout", "labels": [{"name": "feature", "value": "Workouts"}, {"name": "story", "value": "Create Workout"}, {"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_workouts"}, {"name": "host", "value": "Abhay-PC"}, {"name": "thread", "value": "27920-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_workouts"}]}